import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-primary-container": "#f4fffc",
                "tertiary-container": "#00873b",
                "surface-variant": "#d3e4fe",
                "on-secondary": "#ffffff",
                "error": "#ba1a1a",
                "secondary-fixed": "#cce5ff",
                "primary-fixed-dim": "#6bd8cb",
                "on-tertiary": "#ffffff",
                "on-error": "#ffffff",
                "on-tertiary-fixed-variant": "#005321",
                "on-error-container": "#93000a",
                "tertiary-fixed-dim": "#4ae176",
                "primary": "#00685f",
                "on-primary": "#ffffff",
                "background": "#f8f9ff",
                "surface-dim": "#cbdbf5",
                "surface-container": "#e5eeff",
                "inverse-surface": "#213145",
                "surface-bright": "#f8f9ff",
                "secondary-fixed-dim": "#93ccff",
                "on-secondary-fixed-variant": "#004b73",
                "inverse-primary": "#6bd8cb",
                "surface-container-low": "#eff4ff",
                "primary-container": "#008378",
                "secondary": "#006398",
                "surface-container-high": "#dce9ff",
                "on-tertiary-container": "#f7fff3",
                "surface-container-highest": "#d3e4fe",
                "surface-container-lowest": "#ffffff",
                "on-background": "#0b1c30",
                "tertiary-fixed": "#6bff8f",
                "on-tertiary-fixed": "#002109",
                "on-secondary-fixed": "#001d31",
                "on-surface-variant": "#3d4947",
                "on-surface": "#0b1c30",
                "inverse-on-surface": "#eaf1ff",
                "error-container": "#ffdad6",
                "on-secondary-container": "#00476e",
                "surface-tint": "#006a61",
                "outline": "#6d7a77",
                "surface": "#f8f9ff",
                "outline-variant": "#bcc9c6",
                "on-primary-fixed-variant": "#005049",
                "tertiary": "#006b2d",
                "primary-fixed": "#89f5e7",
                "secondary-container": "#5bb8fe",
                "on-primary-fixed": "#00201d"
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            spacing: {
                "widget-gap": "20px",
                "table-cell-padding": "12px 16px",
                "gutter": "16px",
                "container-padding": "24px",
                "unit": "4px"
            },
            fontFamily: {
                "headline-lg": ["Geist", ...defaultTheme.fontFamily.sans],
                "body-lg": ["Geist", ...defaultTheme.fontFamily.sans],
                "headline-md": ["Geist", ...defaultTheme.fontFamily.sans],
                "body-md": ["Geist", ...defaultTheme.fontFamily.sans],
                "mono-data": ["Geist Mono", ...defaultTheme.fontFamily.mono],
                "title-lg": ["Geist", ...defaultTheme.fontFamily.sans],
                "display-lg": ["Geist", ...defaultTheme.fontFamily.sans],
                "label-md": ["Geist", ...defaultTheme.fontFamily.sans],
                "sans": ["Geist", ...defaultTheme.fontFamily.sans],
            },
            fontSize: {
                "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
                "mono-data": ["13px", {"lineHeight": "18px", "fontWeight": "500"}],
                "title-lg": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
                "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}]
            }
        },
    },
    plugins: [forms],
};
