<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>@yield('doc-title', 'Report')</title>
    <style>
        * { font-family: DejaVu Sans, sans-serif; }
        body { font-size: 11px; color: #1f2937; margin: 0; }
        .header { border-bottom: 2px solid #059669; padding-bottom: 8px; margin-bottom: 14px; }
        .header h1 { margin: 0; font-size: 18px; color: #065f46; }
        .header .pharmacy { font-size: 13px; font-weight: bold; }
        .header .meta { color: #6b7280; font-size: 10px; margin-top: 2px; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th, td { text-align: left; padding: 6px 8px; border-bottom: 1px solid #e5e7eb; }
        th { background: #f3f4f6; text-transform: uppercase; font-size: 9px; color: #374151; }
        .right { text-align: right; }
        tfoot td { font-weight: bold; background: #f9fafb; border-top: 2px solid #d1d5db; }
        .summary { width: 100%; margin-bottom: 12px; }
        .summary td { border: none; padding: 4px 8px; }
        .summary .label { color: #6b7280; font-size: 10px; }
        .summary .value { font-size: 14px; font-weight: bold; }
        .footer { position: fixed; bottom: -20px; left: 0; right: 0; text-align: center; color: #9ca3af; font-size: 9px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="pharmacy">{{ $pharmacy->name ?? config('app.name', 'ArogyaKart') }}</div>
        <h1>@yield('doc-title', 'Report')</h1>
        <div class="meta">
            Period: {{ $start->format('d M Y') }} &ndash; {{ $end->format('d M Y') }}
            &nbsp;|&nbsp; Generated: {{ now()->format('d M Y, h:i A') }}
        </div>
    </div>

    @yield('body')

    <div class="footer">Generated by {{ config('app.name', 'ArogyaKart') }} &mdash; page </div>
</body>
</html>
